---
title: "055: Rush Defense"
date: "2023-10-29"
categories:
  - gt_table
format:
  html:
    code-fold: true
    code-summary: "Code"
editor: visual
---

### Load data

```{r load-data, message = FALSE}
# function to loop through years 
# years <- 2004:2023

# regular_season <- data.frame()

# for (year in years) {
  
#  team_stats <- cfbfastR::cfbd_game_team_stats(
#    year = year,
#    season_type = "regular",
#    team = "North Carolina",
#    rows_per_team = 1
#  ) |> 
#    dplyr::select(opponent, rushing_attempts_allowed, 
#                  rushing_yards_allowed, 
#                  yards_per_rush_attempt_allowed, 
#                  rush_tds_allowed)
  
#  team_stats <- team_stats |> 
#    dplyr::mutate(year = year) |> 
#    dplyr::relocate(year, .before = opponent)
  
#  regular_season <- rbind(regular_season, team_stats) |> 
#    dplyr::mutate_at(dplyr::vars(-opponent), as.numeric) # |> 
#    dplyr::arrange(-rushing_yards_allowed)
  
# }

# return(regular_season)

# }

wc <- readr::read_csv("wc.csv")
```

### GT Athletic Theme

```{r gt-theme, warning=FALSE}

gt_theme_athletic <- function(gt_object, ...) {
  
  # get id, if one is passed through to use with CSS
  table_id <- subset(gt_object[['_options']], parameter == 'table_id')$value[[1]]
  
  table <- gt_object |> 
    # set table font
    gt::opt_table_font(
      font = list(
        gt::google_font('Spline Sans Mono'),
        gt::default_fonts()
      ),
      weight = 500
    ) |> 
    # set the column label font and style
    gt::tab_style(
      locations = gt::cells_column_labels(
        columns = gt::everything()
      ),
      style = gt::cell_text(
        font = gt::google_font('Work Sans'),
        weight = 650,
        size = gt::px(14),
        transform = 'uppercase', # column labels to uppercase
        align = 'left'
      )
    ) |> 
    gt::tab_style(
      locations = gt::cells_title('title'),
      style = gt::cell_text(
        font = gt::google_font('Work Sans'),
        weight = 650
      )
    ) |> 
    gt::tab_style(
      locations = gt::cells_title('subtitle'),
      style = gt::cell_text(
        font = gt::google_font('Work Sans'),
        weight = 500
      )
    ) |>
    # set think black column sep.
    gt::tab_style(
      style = gt::cell_borders(sides = 'left', weight = gt::px(0.5), color = 'black'),
      locations = gt::cells_body(
        # everything but the first column
        columns = c(-names(gt_object[['_data']])[1])
      )
    ) |> 
    # set thin dotted row sep.
    gt::tab_style(
      style = gt::cell_borders(sides = "top", color = 'black', weight = gt::px(1.5), style = 'dotted'),
      locations = gt::cells_body(
        rows = gt::everything()
      )
    )|>
    # left align cell text
    gt::cols_align(
      align = 'left',
      columns = gt::everything()
    ) |> 
    gt::tab_options(
      table.font.size = 14,
      column_labels.border.bottom.width = 2,
      column_labels.border.bottom.color = 'black',
      column_labels.border.top.color = 'white',
      row_group.border.bottom.color = 'white',
      table.border.top.style = 'none',
      table.border.bottom.style = 'none',
      heading.border.bottom.style = 'none',
      heading.align = 'left',
      heading.title.font.size = gt::px(30),
      source_notes.border.lr.style = 'none',
      source_notes.font.size = 10
    )
  
  # add css if table id is passed through
  table <- if(!is.null(table_id)) {
    table |> 
      # remove the border from the bottom cell
      gt::opt_css(
        paste0("#", table_id, " tbody tr:last-child {border-bottom: 2px solid #ffffff00;}"),
        add = TRUE
      )
  }
  
  return(table)
  
}
```

### GT Table

```{r gt-table, warning=FALSE}
rush_table <- wc |> 
  dplyr::mutate(logo = opponent) |>
  dplyr::relocate(logo, .before = opponent) |>
  dplyr::select(year, logo, opponent, result, 
               score, rushing_attempts_allowed, rushing_yards_allowed, yards_per_rush_attempt_allowed) |> 
  dplyr::arrange(-yards_per_rush_attempt_allowed) |>
  gt::gt() |>
  gt::cols_label(
    # rename columns
    year = "Season",
    logo = "",
    opponent = "Opponent",
    rushing_attempts_allowed = "Attempts",
    rushing_yards_allowed = "Yards",
    yards_per_rush_attempt_allowed = "Yds/Att"
  ) |>
  gt::tab_spanner(label = "Rush Defense",
                  columns = c(rushing_attempts_allowed, rushing_yards_allowed, yards_per_rush_attempt_allowed)) |>
  cfbplotR::gt_fmt_cfb_logo(columns = "logo") |>
  gt::data_color(
    columns = c(yards_per_rush_attempt_allowed),
    colors = scales::col_numeric(
      c(
        "lightpink",
        "#CBC3E3"
      ),
      domain = NULL
    )
  ) |>
  gtExtras::gt_highlight_rows(
    rows = c(8),
    fill = "#ffffd8",
    bold_target_only = FALSE
  ) |> 
  gt::tab_header(title = "North Carolina's Ugly Rush Defense", subtitle = "Highest yards per rush attempt by an opponent in a single game since 2009 season.") |>
  gt::tab_source_note(source_note = "Bless your chart | October 29 | data via SportSourceAnalytics + gt athletic theme from @andreweatherman")  |>
  gt_theme_athletic() |>
  gt::tab_style(style = list(gt::cell_borders(
    sides = c("left"),
    color = "#c1c1c1",
    weight = gt::px(2)
  )),
  locations = list(gt::cells_body(columns = c(result, rushing_attempts_allowed))))

gtExtras::gtsave_extra(rush_table,
                       filename = "rush.png",
                       vheight = 875,
                       vwidth = 650)

rush_table
```

### 
